In [1]:
import pandas as pd
import requests

ModuleNotFoundError: No module named 'requests'

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [ ]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
df.head()

In [2]:
df = pd.DataFrame()

In [3]:
df

Empty DataFrame
Columns: []
Index: []

In [4]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

# ignore_index = True makes sure we do not repeat indexes starting from 0 again all over but continue where left off

NameError: name 'requests' is not defined

In [5]:
df

Empty DataFrame
Columns: []
Index: []

In [6]:
df.shape

(0, 0)

In [7]:
df.to_csv('movies.csv')